### ISSUE TITLE
Add ES translation

### ISSUE THREAD

**Issue by Netkas** [intellivoid/Translations#1]
Spanish Translations can prove to be useful for potential users.

**Comment by penn5** [comment]
@Netkas Can't Lydia do the translations?

**Comment by Netkas** [comment]
@penn5 No

**Comment by Netkas** [comment]
@penn5 CoffeeHouse does not have translation capabilities. Lydia does not know how to translate text "A" to "B", the AI is only capable of connecting a series of text together to find the best path depending on the emotional state and current scope step.

**Comment by AntiEngineer** [comment]
Please send me a template to translate. Or send to @mdelahozl 

Thanks.

**Comment by mdelahozl** [comment]
@AntiEngineer Sure thing.

**Comment by Netkas** [comment]
@AntiEngineer Check the source code.

**Comment by nypromaniac** [comment]
Any chances for ZH via Intellivoid Accounts? Some of these web applications needs to be updated for example CoffeeHouse needs to be listed in the main landing page. I'm assuming when it does, it needs to be translated as well. Right?

**Comment by mariajose13** [comment]
I'm working in the spanish translation, Will update shortly!!!

**Comment by Netkas** [comment]
> I'm working in the spanish translation, Will update shortly!!!

Please be patient! these translation files will be outdated soon. I'm working on a new version
