### ISSUE TITLE
Spanish Translation for Intellivoid Accounts Dashboard

### ISSUE THREAD

**Issue by Netkas** [intellivoid/Translations#16]
I've added the translation file for Intellivoid Accounts Dashboard which consists of more than 500 lines. I cannot translate this yet because I'm busy working on other parts of IVA2.0, I would appreciate it if this can be translated so that i can check if there are any errors. Thanks, much appreciated.

**Comment by takarushi** [comment]
@Netkas I'll be checking this in the next hours, it shouldn't take too long before i end checking them and close this issue

**Comment by Netkas** [comment]
@takarushi Good luck, you will need it. This took me three days.

**Comment by Netkas** [comment]
Added the last translation, Intellivoid Website.

**Comment by nocturn9x** [comment]
@Netkas cool
