### ISSUE TITLE
Outdated parts in 'en' for OpenBlu Web Application

### ISSUE THREAD

**Issue by Netkas** [intellivoid/Translations#2]
It seems like i have forgotten to update 'purchase', maybe further more. I will verify this and push to the iva2.0 branch

**Comment by Netkas** [comment]
Yes, it seems so. I don't know what happened but i remember adding the translation data for 'purchase', perhaps i did not commit it or something during the time i was switching drives.

**Comment by Netkas** [comment]
I have corrected this issue at [82ba2a105ace0f190f4d8bda6b904a72c9771aad](https://github.com/intellivoid/Translations/commit/82ba2a105ace0f190f4d8bda6b904a72c9771aad), the branch `iva2.0` will not have conflicts with the sub-branches such as `iva2.0-zh` or `iva2.0-es`

**Comment by Netkas** [comment]
I forgot the 'severs' translation too

woop, sorry.

**Comment by Netkas** [comment]
Done! [031c0423233da51ed769c4b814ed2647a85a3267](https://github.com/intellivoid/Translations/commit/031c0423233da51ed769c4b814ed2647a85a3267) make sure to `git pull origin iva2.0` in your current branch.

**Comment by AHumbeBarcode** [comment]
@Netkas woop
